### ISSUE TITLE
feat: 버튼 1 기능(face tracking) 구현

### ISSUE THREAD

**Issue by jeoneunjin** [MagincAR/MagicWand#4]
## Description

> face tracking이용해서 버튼 1 기능인 _'머리 위에 꽃 자라게 하기'_ 구현 + 화면 클릭할 때마다 prefab 변경

## Progress
 - [x] 버튼 1 눌렀을 때 카메라 방향 'World'에서 'User'로 변경되도록 구현 
 - [x] 방향 변경된 상태에서 face tracking 기능 활성화 
 - [x] 기능 활성화 된 상태에서 사용자 화면 touch input 있을 때마다 적용되는 prefab 변경 구현
 - [x] 기타 ( 포지션 값 수정을 통해 머리 위에 위치하도록 구현 등)
